services:
    #Reverse Proxy

    reverse-proxy:
        image: caddy:2-alpine
        restart: unless-stopped
        ports:
            - "80:80" # Intercepts basic web traffic to force immediate upgrade
            - "443:443" # Direct HTTPS endpoint gateway
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        environment:
            - DOMAIN_NAME="https://papertrader.cc" # Swap this with your actual target URL string
        command: caddy reverse-proxy --from https://${DOMAIN_NAME} --to http://web-server:8000
        networks:
            - paper-trader-overlay
        depends_on:
            - web-server

    # Market data ingestion layer

    market-service:
        build:
            context: "./market-service"
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - TICKERS=${TICKERS}
            - REDIS_URL=${REDIS_URL}
            - FINNHUB_API_KEY=${FINNHUB_API_KEY}
        networks:
            - paper-trader-overlay
        restart: unless-stopped

    # Trade execution layer

    trading-service:
        build:
            context: "./trading-service"
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_URL=${REDIS_URL}
        networks:
            - paper-trader-overlay
        restart: unless-stopped

    # FastAPI Web Server (GUI)

    web-server:
        build:
            context: "./web-server"
            dockerfile: Dockerfile
        #        ports:
        #            - "8000:8000"
        expose:
            - "8000"
        environment:
            - JWT_SECRET=${JWT_SECRET}
            - JWT_ALGORITHM=${JWT_ALGORITHM}
            - TICKERS=${TICKERS}
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_URL=${REDIS_URL}
            - TRADING_SERVICE_URL=trading-service:50051
            - FORWARDED_ALLOW_IPS=*
        networks:
            - paper-trader-overlay
        depends_on:
            - trading-service
        restart: unless-stopped
        # Add directory for hot updates on html

    # Network definition

networks:
    paper-trader-overlay:
        driver: bridge
        attachable: true
        external: false
volumes:
    caddy_data:
    caddy_config:
