# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\x0etrading_engine\"p\n\x0cTradeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12-\n\ntrade_type\x18\x04 \x01(\x0e\x32\x19.trading_engine.TradeType\"b\n\rTradeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\x12\x17\n\x0f\x65xecution_price\x18\x04 \x01(\x01\"#\n\x10PortfolioRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"U\n\x11PortfolioResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61sh_balance\x18\x02 \x01(\x01\x12\x19\n\x11portfolio_summary\x18\x03 \x01(\t*\x1e\n\tTradeType\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\x32\xb2\x01\n\x0eTradingService\x12K\n\x0c\x45xecuteTrade\x12\x1c.trading_engine.TradeRequest\x1a\x1d.trading_engine.TradeResponse\x12S\n\x0cGetPortfolio\x12 .trading_engine.PortfolioRequest\x1a!.trading_engine.PortfolioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADETYPE']._serialized_start=370
  _globals['_TRADETYPE']._serialized_end=400
  _globals['_TRADEREQUEST']._serialized_start=32
  _globals['_TRADEREQUEST']._serialized_end=144
  _globals['_TRADERESPONSE']._serialized_start=146
  _globals['_TRADERESPONSE']._serialized_end=244
  _globals['_PORTFOLIOREQUEST']._serialized_start=246
  _globals['_PORTFOLIOREQUEST']._serialized_end=281
  _globals['_PORTFOLIORESPONSE']._serialized_start=283
  _globals['_PORTFOLIORESPONSE']._serialized_end=368
  _globals['_TRADINGSERVICE']._serialized_start=403
  _globals['_TRADINGSERVICE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
