# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTrade = channel.unary_unary(
                '/trading_engine.TradingService/ExecuteTrade',
                request_serializer=engine__pb2.TradeRequest.SerializeToString,
                response_deserializer=engine__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.GetPortfolio = channel.unary_unary(
                '/trading_engine.TradingService/GetPortfolio',
                request_serializer=engine__pb2.PortfolioRequest.SerializeToString,
                response_deserializer=engine__pb2.PortfolioResponse.FromString,
                _registered_method=True)


class TradingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ExecuteTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTrade,
                    request_deserializer=engine__pb2.TradeRequest.FromString,
                    response_serializer=engine__pb2.TradeResponse.SerializeToString,
            ),
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=engine__pb2.PortfolioRequest.FromString,
                    response_serializer=engine__pb2.PortfolioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading_engine.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading_engine.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_engine.TradingService/ExecuteTrade',
            engine__pb2.TradeRequest.SerializeToString,
            engine__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading_engine.TradingService/GetPortfolio',
            engine__pb2.PortfolioRequest.SerializeToString,
            engine__pb2.PortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
